# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PSI-SN' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PSI-SN
  pod 'Alamofire'
  pod 'AlamofireImage'
  pod 'AlamofireNetworkActivityIndicator'
  pod 'Tailor'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'M13ProgressSuite'

  target 'PSI-SNTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PSI-SNUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
